In [5]:
COLUMNS = ['Title', 'Salary/USD', 'Equity %', 'Equity/USD','Work Location','Years of Experience','Years at Startup','Stage','Size']

In [6]:
with open('job.html', 'r') as f:

    contents = f.read()

    soup = BeautifulSoup(contents, 'html.parser')

In [8]:

table = soup.find("table") # Find the "table" tag in the page
rows = table.find_all("tr") # Find all the "tr" tags in the table
cy_data = []
for row in rows:
    cells = row.find_all("td") #  Find all the "td" tags in each row
#     cells = cells[] # Select the correct columns
    cy_data.append([cell.text for cell in cells]) # For each "td" tag, get the text inside it

df = pd.DataFrame(cy_data, columns=COLUMNS)

In [9]:
df.to_csv('jobs.csv')

In [11]:
df

,Title,Salary/USD,Equity %,Equity/USD,Work Location,Years of Experience,Years at Startup,Stage,Size
0,Staff electrical engineer,"$226,000",0.002%,"$650,000",San Francisco,8.0,3.0,Series H,1001-5000 employees
1,Sales development representative,"$95,000",0.0%,-,Remote,1.0,1.0,Series H,1001-5000 employees
2,Product manager,"$286,000",0.002%,"$1,460,000",Remote US,10.0,1.0,Series H,1001-5000 employees
3,Data analytics manager,"$190,000",0.01%,"$126,000",Remote,6.0,4.0,Series H,201-500 employees
4,Senior software engineer,"$160,000",0.002%,-,Remote MX,11.0,0.5,Series G,201-500 employees
...,...,...,...,...,...,...,...,...,...
1114,Forward deployed engineer,"$131,000",0.006%,"$200,000",San Francisco,2.0,2.0,Post-IPO,501-1000 employees
1115,Director of Product,"$305,000",0.056%,"$420,000",Remote US,8.0,4.0,Post-IPO,1001-5000 employees
1116,Director of Marketing & Sales,"$225,000",0.17%,-,Remote,4.0,0.0,Post-IPO,51-100 employees
1117,Design manager,"$195,000",0.005%,"$430,000",Remote US,15.0,2.0,Post-IPO,1001-5000 employees
1118,Product manager,"$121,000",0.5%,-,Austin,5.0,1.0,Bootstrap,1-10 employees